# Generated by Django 5.2.1 on 2025-05-29 16:18

import django.db.models.deletion
import django_extensions.db.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.UUID('7f8b74b4-474f-4334-9321-a0c54532efcb'), editable=False, primary_key=True, serialize=False)),
                ('topic', models.CharField(blank=True, help_text='Tema principal o categorización de la conversación (detectado o asignado manualmente).', max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Campo JSON para metadata adicional y flexible (e.g., source, platform, user_agent).')),
                ('user', models.ForeignKey(blank=True, help_text='El usuario asociado a esta conversación (si aplica).', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.UUID('7f8b74b4-474f-4334-9321-a0c54532efcb'), editable=False, primary_key=True, serialize=False)),
                ('sender_type', models.CharField(choices=[('user', 'User'), ('ai', 'AI')], help_text='Tipo de emisor del mensaje (user o ai).', max_length=50)),
                ('text_content', models.TextField(help_text='El contenido textual del mensaje.')),
                ('token_count', models.IntegerField(blank=True, help_text='Número de tokens utilizados por este mensaje (útil para costos/límites de API).', null=True)),
                ('model_name', models.CharField(blank=True, help_text='Nombre del modelo de IA utilizado para generar la respuesta (e.g., gemini-1.5-flash).', max_length=100, null=True)),
                ('raw_response_data', models.JSONField(blank=True, default=dict, help_text='Datos JSON brutos de la respuesta de la API de IA (si es una respuesta de IA).')),
                ('feedback_rating', models.IntegerField(blank=True, choices=[(1, 'Good'), (0, 'Bad')], help_text='Calificación o feedback del usuario sobre la calidad de la respuesta.', null=True)),
                ('feedback_notes', models.TextField(blank=True, help_text='Notas o comentarios adicionales sobre el feedback.', null=True)),
                ('conversation', models.ForeignKey(help_text='La conversación a la que pertenece este mensaje.', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='gemini.conversation')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['created'],
            },
        ),
    ]
