# Generated by Django 5.2.1 on 2025-05-29 16:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemini', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f50d929d-6004-4a41-aeee-35cfb49a66db'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f50d929d-6004-4a41-aeee-35cfb49a66db'), editable=False, primary_key=True, serialize=False),
        ),
    ]
