# Generated by Django 5.2.1 on 2025-05-29 16:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemini', '0002_alter_conversation_id_alter_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('60f9349b-7c4e-45d0-9364-20610a176c0d'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.UUIDField(default=uuid.UUID('60f9349b-7c4e-45d0-9364-20610a176c0d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
