# Generated by Django 5.2.1 on 2025-05-29 16:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemini', '0003_alter_conversation_id_alter_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('18cec050-4e5d-464b-b17d-a3b69555de83'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.UUIDField(default=uuid.UUID('18cec050-4e5d-464b-b17d-a3b69555de83'), editable=False, primary_key=True, serialize=False),
        ),
    ]
