# Generated by Django 5.2.1 on 2025-05-29 16:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemini', '0004_alter_conversation_id_alter_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('13bfd6ae-54bb-434b-a8c9-e78277da376d'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.UUIDField(default=uuid.UUID('13bfd6ae-54bb-434b-a8c9-e78277da376d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
